//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalMelkBin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdminUser()
        {
            this.RollAdmins = new HashSet<RollAdmin>();
        }
    
        public int id { get; set; }
        public string fullName { get; set; }
        public string telephone { get; set; }
        public string mobile { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public string apiToken { get; set; }
        public Nullable<int> rolId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RollAdmin> RollAdmins { get; set; }
    }
}
