//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalMelkBin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public equipment()
        {
            this.equipmentPictures = new HashSet<equipmentPicture>();
            this.equipmetAcceptUsers = new HashSet<equipmetAcceptUser>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string EquipmentAddress { get; set; }
        public Nullable<int> price { get; set; }
        public string description { get; set; }
        public Nullable<double> lat { get; set; }
        public Nullable<double> lon { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string imageUrl { get; set; }
        public Nullable<int> cityId { get; set; }
        public Nullable<int> subCityId { get; set; }
        public Nullable<int> equipmentCategoriId { get; set; }
        public Nullable<int> equipmentSubCategoriId { get; set; }
        public Nullable<int> childEquipmentSubCategoriId { get; set; }
        public string apiToken { get; set; }
        public string pexpireDate { get; set; }
        public string status { get; set; }
        public Nullable<byte> userType { get; set; }
        public Nullable<int> userId { get; set; }
        public string film { get; set; }
        public string adminComment { get; set; }
        public System.DateTime ExpireDate { get; set; }
    
        public virtual city city { get; set; }
        public virtual childSubEquipmentCategori childSubEquipmentCategori { get; set; }
        public virtual equipmentCategori equipmentCategori { get; set; }
        public virtual equipmentSubCategori equipmentSubCategori { get; set; }
        public virtual equipmetUser equipmetUser { get; set; }
        public virtual subCity subCity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<equipmentPicture> equipmentPictures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<equipmetAcceptUser> equipmetAcceptUsers { get; set; }
    }
}
