//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalMelkBin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public job()
        {
            this.jobAcceptUsers = new HashSet<jobAcceptUser>();
            this.jobPictures = new HashSet<jobPicture>();
        }
    
        public int id { get; set; }
        public Nullable<double> lon { get; set; }
        public Nullable<double> lat { get; set; }
        public string title { get; set; }
        public string JobAddress { get; set; }
        public string fullName { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public Nullable<int> cityId { get; set; }
        public Nullable<int> subCityId { get; set; }
        public Nullable<byte> tahsilat { get; set; }
        public string otherMaharat { get; set; }
        public string sabeghe { get; set; }
        public Nullable<int> jobCategoriId { get; set; }
        public Nullable<int> jobSubCategoriId { get; set; }
        public Nullable<int> childjobSubCategoriId { get; set; }
        public string sharheVazayef { get; set; }
        public string vazayefRoozaneVaHaftegiVaMahane { get; set; }
        public string film { get; set; }
        public string imageUrl { get; set; }
        public string status { get; set; }
        public Nullable<int> userId { get; set; }
        public string Mablagh { get; set; }
        public string pExpire { get; set; }
        public string apiToken { get; set; }
        public Nullable<byte> userType { get; set; }
        public Nullable<byte> advertisementType { get; set; }
        public string adminComment { get; set; }
    
        public virtual city city { get; set; }
        public virtual childjobSubCategori childjobSubCategori { get; set; }
        public virtual jobCategori jobCategori { get; set; }
        public virtual jobSubCategori jobSubCategori { get; set; }
        public virtual jobUser jobUser { get; set; }
        public virtual subCity subCity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<jobAcceptUser> jobAcceptUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<jobPicture> jobPictures { get; set; }
    }
}
