//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalMelkBin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobAcceptUser
    {
        public int id { get; set; }
        public int jobId { get; set; }
        public string userName { get; set; }
        public string statusSelected { get; set; }
        public string registerDate { get; set; }
    
        public virtual job job { get; set; }
    }
}
