//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalMelkBin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class melk
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public melk()
        {
            this.melkAcceptUsers = new HashSet<melkAcceptUser>();
            this.pictures = new HashSet<picture>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string imageUrl { get; set; }
        public string film { get; set; }
        public string telephone { get; set; }
        public string mobile { get; set; }
        public string address { get; set; }
        public double lon { get; set; }
        public double lat { get; set; }
        public string tozihatTakmily { get; set; }
        public byte parking { get; set; }
        public bool isNegahban { get; set; }
        public bool isSystemGarmayeshiMarkazi { get; set; }
        public bool isKabinet { get; set; }
        public bool isHayat { get; set; }
        public bool isSalonEjtema { get; set; }
        public bool isLaby { get; set; }
        public bool isEstakhrVaSona { get; set; }
        public bool isSalonVarzeshi { get; set; }
        public bool isPentHouse { get; set; }
        public bool isFazayeSabz { get; set; }
        public bool IsDastshooyiFarangi { get; set; }
        public bool IsMaster { get; set; }
        public bool vaziyatSokoonat { get; set; }
        public byte mogheiyatJographiya { get; set; }
        public bool isDarbZedSerghat { get; set; }
        public byte kafpoosh { get; set; }
        public byte cooler { get; set; }
        public byte garmayeshi { get; set; }
        public bool isIphoneTasviry { get; set; }
        public bool isAntenMarkazi { get; set; }
        public byte divar { get; set; }
        public byte saghf { get; set; }
        public bool isKomodDivari { get; set; }
        public bool isPangerehDojedareh { get; set; }
        public byte typeDastebandi { get; set; }
        public long gheymateForoosh { get; set; }
        public byte melkType { get; set; }
        public byte sanad { get; set; }
        public bool sanadType { get; set; }
        public bool typeEskelet { get; set; }
        public int zirbana { get; set; }
        public int tedadTabaghat { get; set; }
        public int tedadVahedDarTabaghe { get; set; }
        public int tedadOtaghkhab { get; set; }
        public Nullable<int> buildDateId { get; set; }
        public Nullable<int> cityId { get; set; }
        public Nullable<int> categoriId { get; set; }
        public bool isVip { get; set; }
        public string pExpireDate { get; set; }
        public System.DateTime expireDate { get; set; }
        public string statusId { get; set; }
        public Nullable<int> subCityId { get; set; }
        public Nullable<int> subCategoriId { get; set; }
        public Nullable<int> childSubCategoriId { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<long> gheymateRahn { get; set; }
        public Nullable<long> gheymateEjareh { get; set; }
        public Nullable<bool> ghabeleTabdilBarayeRahn { get; set; }
        public Nullable<bool> ghabeleTabdilBarayeEjareh { get; set; }
        public Nullable<byte> userType { get; set; }
        public string adminComment { get; set; }
    
        public virtual buildDate buildDate { get; set; }
        public virtual Categori Categori { get; set; }
        public virtual city city { get; set; }
        public virtual ChildSubCategori ChildSubCategori { get; set; }
        public virtual SubCategori SubCategori { get; set; }
        public virtual subCity subCity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<melkAcceptUser> melkAcceptUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<picture> pictures { get; set; }
        public virtual user user { get; set; }
    }
}
