//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalMelkBin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.melks = new HashSet<melk>();
        }
    
        public int id { get; set; }
        public string fullName { get; set; }
        public string telephone { get; set; }
        public string mobile { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public string apiToken { get; set; }
        public Nullable<int> rolId { get; set; }
        public string abutMe { get; set; }
        public Nullable<byte> userType { get; set; }
        public string userImageUrl { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<melk> melks { get; set; }
        public virtual roll roll { get; set; }
    }
}
